# Configuration for Travis-CI

language: java

dist: xenial
os: linux

# Environment variables for all the OS
env:
  global:
    - MAVEN_VERSION: "3.6.3"
    - MAVEN_OPTS: "-XX:+CMSClassUnloadingEnabled -Xmx3g" 
    - MAVEN_COMPILATION_OPTS: "\"-e -P!generateproduct -Dgroups=!sre-run -Dio.sarl.docs.tests.skip=true\""
    - HTTPS_KEYSTORE_FILE: "./build-tools/keyring/https.jks"

# Compilation matrix
jobs:
  fast_finish: true
  include:
    - os: osx
      osx_image: xcode8.3 # see https://docs.travis-ci.com/user/osx-ci-environment/
      before_install:
      - echo "MAVEN_OPTS=\"$MAVEN_OPTS\"" > $HOME/.mavenrc

install: true

script: "sh -e ./build-tools/scripts/travis-maven-compile.sh"

cache:
  directories:
  - $HOME/.m2
  - $HOME/.binaries

